name: uncommon-dylan-test-suite

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  buld-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Open Dylan
        uses: dylan-lang/install-opendylan@v3

      - name: Update Dylan workspace
        run: |
          dylan update

      - name: Build test suite
        run: |
          dylan build uncommon-dylan-test-suite

      - name: Run test suite
        run: |
          _build/bin/uncommon-dylan-test-suite --report surefire --report-file _build/uncommon-dylan-tests.xml

      - name: Publish test report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/_build/*-tests.xml'
          detailed_summary: true
          include_passed: true
