name: uncommon-dylan-test-suite

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  # This is the name you have to search for when enabling branch protection
  # mechanisms in the repository settings. (Not mentioned in the docs as far as
  # I can tell?)
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dylan-lang/install-dylan-tool@v2

      - name: Update workspace
        run: |
          ../dylan --verbose update

      - name: Build test suite
        run: |
          ../dylan-compiler -build uncommon-dylan-test-suite

      - name: Run test suite
        run: |
          ./_build/bin/uncommon-dylan-test-suite
